CREATE TABLE t1 (a INTEGER, b CHAR(10));

ALTER TABLE t1
	RENAME t2;

ALTER TABLE t2
	MODIFY COLUMN a TINYINT NOT NULL;

ALTER TABLE t2
    MODIFY COLUMN b CHAR (20),
    RENAME COLUMN b to c;
    
ALTER TABLE t2
	ADD COLUMN d TIMESTAMP;
    
ALTER TABLE t2
	DROP COLUMN c;

CREATE TABLE t3 AS
	SELECT * 
    FROM t2;

DROP TABLE t2;
ALTER TABLE t3
	RENAME t1;
    